#!/usr/bin/env python3
"""Add a stream HRU to the GRUs of a bundled SUMMA domain, for the stream temperature test.

A stream HRU holds the water column of the reach its GRU drains to: a `stream`
domain (domType = 6) with lake layers over the soil, no upland domain, and an
area equal to the reach planform area (length x width, with the width mizuRoute
would derive from the drainage area). The land HRU of the GRU gives up that
area, so the GRU area -- and the runoff mizuRoute receives per unit area -- is
unchanged. GRUs too small to hold their reach get no stream HRU, which also
exercises the reaches that only mix what flows into them.

Writes a complete settings directory (attributes, cold state, trial parameters,
forcing, and copies of the text settings) next to the original one. The river
network itself still comes from make_test_topology.py, run on the new
attributes file.

Usage:
    make_stream_domain.py <domain dir> <work settings dir> <work forcing dir>
"""

import os
import shutil
import sys
import warnings

import numpy as np
from netCDF4 import Dataset

warnings.filterwarnings("ignore", category=DeprecationWarning)

# the stream domain type in globalData.f90, and the USGS water class
STREAM = 6
UPLAND = 1
VEG_WATER = 16
# reach geometry, as make_test_topology.py and the mizuRoute default parameters (wscale)
SEGMENT_LENGTH_M = 5000.0
WSCALE = 0.001
# lake layers of the water column: a thin top layer where ice forms, the rest below
LAKE_DEPTHS = [0.2, 0.8]
LAKE_TEMP_K = 278.0
STREAM_ID_OFFSET = 100000


def copy_var(src, dst, name, dims=None, data=None, dtype=None):
    v = src.variables[name]
    fill = v.getncattr("_FillValue") if "_FillValue" in v.ncattrs() else None
    out = dst.createVariable(name, dtype or v.dtype, dims or v.dimensions, fill_value=fill)
    for att in v.ncattrs():
        if att != "_FillValue":
            out.setncattr(att, v.getncattr(att))
    out[:] = v[:] if data is None else data
    return out


def main(domain_dir, work_settings, work_forcing):
    src_settings = os.path.join(domain_dir, "settings", "SUMMA")
    src_forcing = os.path.join(domain_dir, "forcing", "SUMMA_input")
    os.makedirs(work_settings, exist_ok=True)
    os.makedirs(work_forcing, exist_ok=True)

    # ------------------------------------------------------------------ attributes --
    with Dataset(os.path.join(src_settings, "attributes.nc")) as a:
        hru_id = np.array(a.variables["hruId"][:], dtype="i8")
        gru_id = np.array(a.variables["gruId"][:], dtype="i8")
        hru2gru = np.array(a.variables["hru2gruId"][:], dtype="i8")
        hru_area = np.array(a.variables["HRUarea"][:], dtype="f8")
        n_hru, n_gru = len(hru_id), len(gru_id)
        if n_hru != n_gru or not np.array_equal(hru2gru, gru_id):
            sys.exit("expected one HRU per GRU, in GRU order")

        # the chain of make_test_topology.py: GRU i drains to reach i, which drains to reach i+1
        up_area = np.cumsum(hru_area)
        width = WSCALE * np.sqrt(up_area)
        stream_area = SEGMENT_LENGTH_M * width
        # a few bundled GRUs are smaller than their reach: those keep no stream HRU
        keep = stream_area < 0.5 * hru_area
        seg_id = np.arange(1, n_gru + 1, dtype="i4")
        n_str = int(keep.sum())
        s_ix = np.flatnonzero(keep)          # land HRU index of each stream HRU

        with Dataset(os.path.join(work_settings, "attributes.nc"), "w", format="NETCDF4") as d:
            d.createDimension("hru", n_hru + n_str)
            d.createDimension("gru", n_gru)
            for name, v in a.variables.items():
                if v.dimensions == ("gru",):
                    copy_var(a, d, name)
                    continue
                land = np.array(v[:])
                stream = land[s_ix].copy()
                if name == "hruId":
                    stream = stream + STREAM_ID_OFFSET
                elif name == "HRUarea":
                    land = np.where(keep, land - stream_area, land)
                    stream = stream_area[s_ix]
                elif name == "vegTypeIndex":
                    stream = np.full_like(stream, VEG_WATER)
                elif name == "downHRUindex":
                    stream = np.zeros_like(stream)
                copy_var(a, d, name, data=np.concatenate([land, stream]))
            v = d.createVariable("streamSegId", "i4", ("hru",))
            v.long_name = "mizuRoute reach id of a stream HRU (0 = reach mapped from the GRU id)"
            v.units = "-"
            v[:] = np.concatenate([np.zeros(n_hru, dtype="i4"), seg_id[s_ix]])
            d.description = "bundled domain with a stream HRU per GRU, generated by make_stream_domain.py"

    # ------------------------------------------------------------------ cold state --
    with Dataset(os.path.join(src_settings, "coldState.nc")) as c:
        n_soil = int(np.array(c.variables["nSoil"][:]).max())
        n_lake = len(LAKE_DEPTHS)
        n_toto = n_soil + n_lake
        depth = np.array(c.variables["mLayerDepth"][:], dtype="f8")     # (midToto, hru)
        temp = np.array(c.variables["mLayerTemp"][:], dtype="f8")
        liq = np.array(c.variables["mLayerVolFracLiq"][:], dtype="f8")
        ice = np.array(c.variables["mLayerVolFracIce"][:], dtype="f8")
        mhead = np.array(c.variables["mLayerMatricHead"][:], dtype="f8")  # (midSoil, hru)

        with Dataset(os.path.join(work_settings, "coldState.nc"), "w", format="NETCDF4") as d:
            d.createDimension("hru", n_hru + n_str)
            d.createDimension("dom", 2)
            d.createDimension("scalarv", 1)
            d.createDimension("midSoil", n_soil)
            d.createDimension("midToto", n_toto)
            d.createDimension("ifcToto", n_toto + 1)

            def scal(name, land, stream_up, stream_dom, units, long_name, dtype="f8"):
                # dims (scalarv, hru, dom): land HRU has only its upland domain, stream HRU an empty upland and the stream
                # (stream_up and stream_dom are given per land HRU and taken for the kept ones)
                v = d.createVariable(name, dtype, ("scalarv", "hru", "dom"))
                v.units, v.long_name = units, long_name
                arr = np.zeros((1, n_hru + n_str, 2), dtype=dtype)
                arr[0, :n_hru, 0] = land
                arr[0, :n_hru, 1] = land          # unused, but must not be the fill value
                arr[0, n_hru:, 0] = np.broadcast_to(stream_up, (n_hru,))[s_ix]
                arr[0, n_hru:, 1] = np.broadcast_to(stream_dom, (n_hru,))[s_ix]
                v[:] = arr

            def layered(name, dim, nlay, land, stream_dom, units, long_name):
                # dims (layer, hru, dom)
                v = d.createVariable(name, "f8", (dim, "hru", "dom"))
                v.units, v.long_name = units, long_name
                arr = np.zeros((nlay, n_hru + n_str, 2))
                arr[: land.shape[0], :n_hru, 0] = land
                arr[: land.shape[0], :n_hru, 1] = land
                arr[: land.shape[0], n_hru:, 0] = land[:, s_ix]
                arr[:, n_hru:, 1] = stream_dom[:, s_ix]
                v[:] = arr

            v = d.createVariable("hruId", "i8", ("hru",))
            v[:] = np.concatenate([hru_id, hru_id[s_ix] + STREAM_ID_OFFSET])
            v = d.createVariable("domType", "i4", ("hru", "dom"))
            v.long_name = "type defining the domain response unit type"
            dt = np.zeros((n_hru + n_str, 2), dtype="i4")
            dt[:, 0] = UPLAND
            dt[n_hru:, 1] = STREAM
            v[:] = dt
            for name, val in (("nSnow", 0), ("nSoil", n_soil), ("nGlce", 0)):
                v = d.createVariable(name, "i4", ("hru", "dom"))
                v[:] = np.full((n_hru + n_str, 2), val, dtype="i4")
            v = d.createVariable("nLake", "i4", ("hru", "dom"))
            nl = np.zeros((n_hru + n_str, 2), dtype="i4")
            nl[n_hru:, 1] = n_lake
            v[:] = nl

            def scalar_src(name):
                return np.array(c.variables[name][:], dtype="f8").reshape(-1)[:n_hru]

            # scalar states: the stream domain is bare open water at the lake temperature
            for name in ("dt_init", "scalarCanopyIce", "scalarCanopyLiq", "scalarSnowDepth", "scalarSWE",
                         "scalarSfcMeltPond", "scalarAquiferStorage", "scalarSnowAlbedo",
                         "scalarCanairTemp", "scalarCanopyTemp"):
                land = scalar_src(name)
                stream = land.copy()
                if name in ("scalarCanopyIce", "scalarCanopyLiq", "scalarSnowDepth", "scalarSWE", "scalarSfcMeltPond"):
                    stream[:] = 0.0
                if name in ("scalarCanairTemp", "scalarCanopyTemp"):
                    stream[:] = LAKE_TEMP_K
                src = c.variables[name]
                scal(name, land, stream, stream, getattr(src, "units", "-"), getattr(src, "long_name", name))

            # domain geometry: the stream takes its reach area, the upland domain of the stream HRU is empty
            with Dataset(os.path.join(work_settings, "attributes.nc")) as a:
                elev = np.array(a.variables["elevation"][:n_hru], dtype="f8")
                tan_slope = np.array(a.variables["tan_slope"][:n_hru], dtype="f8")
                aspect = np.array(a.variables["aspect"][:n_hru], dtype="f8")
                contour = np.array(a.variables["contourLength"][:n_hru], dtype="f8")
            scal("DOMarea", np.where(keep, hru_area - stream_area, hru_area), np.zeros(n_hru), stream_area, "m2", "area of the domain")
            scal("DOMelev", elev, elev, elev, "m", "elevation of the domain")
            scal("DOMtan_slope", tan_slope, tan_slope, tan_slope, "-", "tan local ground surface slope of the domain")
            scal("DOMaspect", aspect, aspect, aspect, "degrees", "azimuth in degrees East of North of the domain")
            scal("DOMcontourLength", contour, contour, np.full(n_hru, SEGMENT_LENGTH_M), "m",
                 "length of contour at downslope edge of the domain")

            # layered states: lake layers on top of the land soil column
            lake_depth = np.tile(np.array(LAKE_DEPTHS)[:, None], (1, n_hru))
            s_depth = np.vstack([lake_depth, depth[:n_soil]])
            s_temp = np.vstack([np.full((n_lake, n_hru), LAKE_TEMP_K), temp[:n_soil]])
            s_liq = np.vstack([np.ones((n_lake, n_hru)), liq[:n_soil]])
            s_ice = np.vstack([np.zeros((n_lake, n_hru)), ice[:n_soil]])
            layered("mLayerDepth", "midToto", n_toto, depth, s_depth, "m", "depth of each layer")
            layered("mLayerTemp", "midToto", n_toto, temp, s_temp, "K", "temperature of each layer")
            layered("mLayerVolFracLiq", "midToto", n_toto, liq, s_liq, "-", "volumetric fraction of liquid water in each layer")
            layered("mLayerVolFracIce", "midToto", n_toto, ice, s_ice, "-", "volumetric fraction of ice in each layer")
            layered("mLayerMatricHead", "midSoil", n_soil, mhead, mhead, "m", "matric head of water in the soil")
            # interface heights: soil top at zero, lake layers above it (negative), soil below
            land_h = np.array(c.variables["iLayerHeight"][:], dtype="f8")
            s_h = np.zeros((n_toto + 1, n_hru))
            s_h[0] = -sum(LAKE_DEPTHS)
            for k in range(n_toto):
                s_h[k + 1] = s_h[k] + s_depth[k]
            layered("iLayerHeight", "ifcToto", n_toto + 1, land_h, s_h, "m", "height of the layer interface; top of soil = 0")

    # ------------------------------------------------------------ trial parameters --
    with Dataset(os.path.join(src_settings, "trialParams.nc")) as p, \
         Dataset(os.path.join(work_settings, "trialParams.nc"), "w", format="NETCDF4") as d:
        d.createDimension("hru", n_hru + n_str)
        d.createDimension("gru", n_gru)
        for name, v in p.variables.items():
            if v.dimensions == ("gru",):
                copy_var(p, d, name)
            else:
                land = np.array(v[:])
                stream = land[s_ix] + STREAM_ID_OFFSET if name == "hruId" else land[s_ix]
                copy_var(p, d, name, data=np.concatenate([land, stream]))

    # ------------------------------------------------------------------- forcing --
    with open(os.path.join(src_settings, "forcingFileList.txt")) as f:
        forcing_files = [ln.strip().strip("'\"") for ln in f if ln.strip()]
    for fname in forcing_files:
        with Dataset(os.path.join(src_forcing, fname)) as s, \
             Dataset(os.path.join(work_forcing, fname), "w", format="NETCDF4") as d:
            for dname, dim in s.dimensions.items():
                d.createDimension(dname, n_hru + n_str if dname == "hru" else (None if dim.isunlimited() else len(dim)))
            for name, v in s.variables.items():
                if "hru" not in v.dimensions:
                    copy_var(s, d, name)
                    continue
                ax = v.dimensions.index("hru")
                land = np.array(v[:])
                stream = np.take(land, s_ix, axis=ax)
                if name == "hruId":
                    stream = stream + STREAM_ID_OFFSET
                copy_var(s, d, name, data=np.concatenate([land, stream], axis=ax))
    shutil.copy(os.path.join(src_settings, "forcingFileList.txt"), work_settings)

    # ------------------------------------------------------------ text settings --
    for fname in os.listdir(src_settings):
        if fname.endswith((".txt", ".TBL")) and fname != "forcingFileList.txt":
            shutil.copy(os.path.join(src_settings, fname), work_settings)
    # add the stream variables to the output
    with open(os.path.join(work_settings, "outputControl.txt"), "a") as f:
        f.write("\nscalarStreamTemp | 1\nscalarStreamDepth | 1\nscalarStreamVelocity | 1\nscalarStreamInflow | 1\n"
                "scalarStreamInflowTemp | 1\nscalarStreamLatInflow | 1\nscalarStreamLatInflowTemp | 1\n"
                "scalarLakeLiqDepth | 1\nmLayerLakeAdvNrgFlux | 1\nbalanceLakeNrg | 1\nmLayerTemp | 1\n"
                "mLayerVolFracIce | 1\naverageRoutedRunoffTemp | 1\nscalarStreamRunoff | 1\n")

    print(f"wrote {work_settings}: {n_hru} land HRUs + {n_str} stream HRUs ({n_hru - n_str} GRUs too small for a reach)")
    print(f"reach width {width.min():.1f}-{width.max():.1f} m, stream area {stream_area.min():.3e}-{stream_area.max():.3e} m2")


if __name__ == "__main__":
    if len(sys.argv) != 4:
        sys.exit(__doc__)
    main(sys.argv[1], sys.argv[2], sys.argv[3])
