#!/usr/bin/env bash
set -euo pipefail

# ==============================================================================
# Stream temperature test on a bundled domain
#
# Gives every GRU of the bundled Provo domain a stream HRU (the water column of
# the reach it drains to) and routes the domain through the synthetic chain
# network of make_test_topology.py. Checks that the coupled run completes,
# that the runoff handed to mizuRoute is still the SUMMA runoff, that the reach
# temperatures stay physical, and that the water column freezes when the air
# does. Not a comparison against observations.
#
# Requires a build configured with -DUSE_MIZUROUTE=ON, and python3 with netCDF4.
# ==============================================================================

SUMMA_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
SUMMA_EXE="$SUMMA_ROOT/bin/summa_sundials_mizuroute.exe"
DOMAIN="$SUMMA_ROOT/utils/test/test_ngen/domain_provo"
FILE_MANAGER="$DOMAIN/settings/SUMMA/fileManager.txt"

WORK_DIR="${1:-$SUMMA_ROOT/utils/test/test_mizuroute/stream_prob}"
SUFFIX="stream_prob"
# the bundled forcing covers Oct-Dec 2017: long enough for the reaches to cool and freeze
SIM_END="${SIM_END:-2017-12-31 23:00}"

echo
echo "======================================================================"
echo "SUMMA stream temperature test (bundled domain, synthetic network)"
echo "======================================================================"
echo "  executable:   $SUMMA_EXE"
echo "  work dir:     $WORK_DIR"
echo

if [[ ! -f "$SUMMA_EXE" ]]; then
  echo "ERROR: $SUMMA_EXE not found (needs a mizuRoute build)"; exit 1
fi

mkdir -p "$WORK_DIR/settings/SUMMA" "$WORK_DIR/forcing" "$WORK_DIR/output"

# ------------------------------------------------- domain with stream HRUs --
echo "Adding a stream HRU to every GRU..."
python3 "$SUMMA_ROOT/utils/test/test_mizuroute/make_stream_domain.py" \
        "$DOMAIN" "$WORK_DIR/settings/SUMMA" "$WORK_DIR/forcing"

echo "Building synthetic river network..."
python3 "$SUMMA_ROOT/utils/test/test_mizuroute/make_test_topology.py" \
        "$WORK_DIR/settings/SUMMA/attributes.nc" \
        "$WORK_DIR/settings/topology.nc"

cp "$SUMMA_ROOT/external/mizuRoute/route/ancillary_data/param.nml.default" "$WORK_DIR/settings/"

cat > "$WORK_DIR/config.toml" <<TOML
# generated by test_streamtemp_bundled.sh

[simulation]
use_mizuroute = true

[mizuRoute]
namelist_path = "$WORK_DIR/settings/"
namelist_file = "param.nml.default"
methods = "3"
dt = 3600
write_qbasin = true
write_Qreach = true

[hydrofabric]
hfabric_path = "$WORK_DIR/settings/"
hfabric_file = "topology.nc"
dname_seg = "seg"
dname_hru = "hru"
varname_HRUid     = "hruId"
varname_segId     = "segId"
varname_hruSegId  = "hruToSegId"
varname_downSegId = "downSegId"
varname_area   = "area"
varname_slope  = "slope"
varname_length = "length"
TOML

sed -e "s|^settingsPath .*|settingsPath         '$WORK_DIR/settings/SUMMA/'|" \
    -e "s|^forcingPath .*|forcingPath          '$WORK_DIR/forcing/'|" \
    -e "s|^outputPath .*|outputPath           '$WORK_DIR/output/'|" \
    -e "s|^simEndTime .*|simEndTime           '$SIM_END'|" \
    "$FILE_MANAGER" > "$WORK_DIR/fileManager.txt"

# ----------------------------------------------------------------------- run --
echo
echo "Running coupled SUMMA-mizuRoute with stream HRUs..."
"$SUMMA_EXE" -m "$WORK_DIR/fileManager.txt" -c "$WORK_DIR/config.toml" -s "$SUFFIX" \
             > "$WORK_DIR/run.log" 2>&1 || true

if ! grep -q "finished simulation successfully" "$WORK_DIR/run.log"; then
  echo "ERROR: run did not complete; see $WORK_DIR/run.log"
  tail -20 "$WORK_DIR/run.log"
  exit 1
fi
echo "  run completed"

# -------------------------------------------------------------------- check --
OUTPUT=$(ls "$WORK_DIR/output/"*"${SUFFIX}"*timestep.nc | head -1)
echo
echo "Checking $(basename "$OUTPUT")..."
python3 - "$OUTPUT" "$WORK_DIR/settings/SUMMA/attributes.nc" "$WORK_DIR/forcing" <<'PYEOF'
import sys, glob
import numpy as np
from netCDF4 import Dataset

output_file, attr_file, forcing_dir = sys.argv[1:4]
TFREEZE = 273.16
fail = False

with Dataset(attr_file) as a:
    seg_of_hru = np.array(a.variables["streamSegId"][:])
    attr_hru_id = np.array(a.variables["hruId"][:])
stream_ids = attr_hru_id[seg_of_hru > 0]                # the stream HRUs
seg_ix = seg_of_hru[seg_of_hru > 0] - 1                 # reach index (segId = 1..n) of each stream HRU

with Dataset(output_file) as d:
    def get(name):
        if name not in d.variables: sys.exit(f"FAIL: {name} missing from the output file")
        return np.ma.filled(d.variables[name][:].astype("f8"), np.nan)
    T_reach = get("T_reach")                 # (time, seg)
    v_reach = get("v_reach")
    n_reach = get("n_reach")
    ice_reach = get("ice_reach")
    q_basin = get("q_basin")                 # (time, mizu_hru)
    runoff = get("averageRoutedRunoff")      # (time, gru)
    T_runoff = get("averageRoutedRunoffTemp")
    T_stream = get("scalarStreamTemp")       # (time, dom, hru)
    ice = get("mLayerVolFracIce")            # (time, midToto, dom, hru) or similar
    bal = get("balanceLakeNrg")
    dims_T = d.variables["scalarStreamTemp"].dimensions
    dims_ice = d.variables["mLayerVolFracIce"].dimensions
    dims_bal = d.variables["balanceLakeNrg"].dimensions
    out_hru_id = np.array(d.variables["hruId"][:])
# the output lists HRUs GRU by GRU, so find the stream HRUs by id
stream = np.array([np.flatnonzero(out_hru_id == i)[0] for i in stream_ids])
airT = []
for f in sorted(glob.glob(forcing_dir + "/*.nc")):
    with Dataset(f) as s: airT.append(np.array(s.variables["airtemp"][:]))
airT = np.concatenate(airT, axis=0)

# the runoff mizuRoute receives is still exactly the SUMMA runoff
if np.nanmax(np.abs(q_basin - runoff)) != 0.0:
    print("FAIL: q_basin does not match SUMMA averageRoutedRunoff"); fail = True
else:
    print("  runoff transfer:   exact")

# reach temperatures: defined everywhere, never below freezing, never above the warmest air of the run
if np.isnan(T_reach).any() or (T_reach < TFREEZE - 1e-6).any():
    print("FAIL: T_reach has missing values or values below freezing"); fail = True
elif T_reach.max() > np.nanmax(airT) + 2.0:
    print(f"FAIL: T_reach max {T_reach.max():.2f} K above the warmest air {np.nanmax(airT):.2f} K"); fail = True
else:
    print(f"  T_reach:           {T_reach.min():.2f} to {T_reach.max():.2f} K (air {np.nanmin(airT):.2f} to {np.nanmax(airT):.2f} K)")

# the stream column of each reach is what its reach reports (same step, same value)
# stream domain is dom index 1 (second) of the stream HRUs
ax_dom = dims_T.index("dom"); ax_hru = dims_T.index("hru")
Ts = np.take(np.take(T_stream, stream, axis=ax_hru), 1, axis=ax_dom)   # (time, stream HRU)
Ts = np.maximum(Ts, TFREEZE)   # the water leaving a frozen column is at the freezing point
if np.nanmax(np.abs(Ts - T_reach[:, seg_ix])) > 1e-9:
    print(f"FAIL: scalarStreamTemp and T_reach disagree by up to {np.nanmax(np.abs(Ts - T_reach[:, seg_ix])):.3e} K"); fail = True
else:
    print(f"  column vs reach:   consistent ({len(stream)} stream HRUs, {T_reach.shape[1] - len(stream)} reaches only mixing)")

# the runoff temperature is physical
if np.isnan(T_runoff).any() or (T_runoff < TFREEZE - 1e-6).any() or T_runoff.max() > np.nanmax(airT) + 10.0:
    print("FAIL: averageRoutedRunoffTemp unphysical"); fail = True
else:
    print(f"  runoff temp:       {T_runoff.min():.2f} to {T_runoff.max():.2f} K")

# freeze-up: after a cold week (mean air well below freezing) some reach must carry an ice cover: a lake
# layer of (nearly) solid ice, which snow (volFracIce below ~0.7) and frozen soil (below theta_sat) never reach
ax_dom = dims_ice.index("dom"); ax_hru = dims_ice.index("hru"); ax_lay = dims_ice.index("midToto")
ice_s = np.take(np.take(ice, stream, axis=ax_hru), 1, axis=ax_dom)   # (time, midToto, stream HRU)
ice_cover = np.any(ice_s > 0.9, axis=ax_lay if ax_lay < ax_dom else ax_lay - 1)
frac_frozen = np.nanmean(ice_cover[-24:])
week_air = np.nanmean(airT[-24*7:])
if week_air < TFREEZE - 3.0 and frac_frozen == 0.0:
    print(f"FAIL: a week of air at {week_air:.1f} K and no reach carries ice"); fail = True
else:
    print(f"  freeze-up:         {100*frac_frozen:.0f}% of reaches ice-covered over the last day (last week air {week_air:.1f} K)")

# velocity from the routing
print(f"  velocity:          {np.nanmin(v_reach):.3f} to {np.nanmax(v_reach):.3f} m s-1")

# the roughness the routing used: the bed value on open water, raised under an ice cover (Wanders et al. 2019 eqs 12-13);
# the routing of a step uses the cover the column had after the previous step
ice_prev = np.vstack([np.zeros_like(ice_reach[:1]), ice_reach[:-1]])
n_open = n_reach[ice_prev <= 0.0]; n_ice = n_reach[ice_prev > 0.0]
n_bed = np.nanmin(n_reach[:, seg_ix])
if n_open.size and np.nanmax(np.abs(n_open - n_bed)) > 1e-12:
    print("FAIL: n_reach differs from the bed roughness on ice-free reaches"); fail = True
elif n_ice.size and np.nanmin(n_ice) <= n_bed:
    print("FAIL: n_reach not raised under an ice cover"); fail = True
else:
    print(f"  roughness:         bed {n_bed:.4f}, under ice up to {np.nanmax(n_ice) if n_ice.size else n_bed:.4f} "
          f"(ice up to {np.nanmax(ice_reach):.3f} m)")

# energy balance of the water column (W m-3), stream domains only
bal_s = np.take(np.take(bal, stream, axis=dims_bal.index("hru")), 1, axis=dims_bal.index("dom"))
print(f"  lake nrg balance:  max |{np.nanmax(np.abs(bal_s)):.3e}| W m-3")
if np.nanmax(np.abs(bal_s)) > 1.0:
    print("FAIL: lake energy balance error above 1 W m-3"); fail = True

sys.exit(1 if fail else 0)
PYEOF

echo
echo "PASS"
echo
