#!/bin/bash
# ---------------------------------------------------------------------------------------
# Two-objective glacier calibration on the bundled Gulkana domain.
#
# NSGA-II on daily discharge (KGE) and the glacier-wide seasonal mass balance (RMSE),
# 2009-2012 after a 2008 spin-up, over four parameters that move snow accumulation, melt
# and glacier runoff. GRACE can stand in for the mass balance (the commented target below);
# scoring both at once pits two measures of the same storage against each other. The
# script checks the front the way test_calibration_bow_pareto.sh does and prints it.
#
# The budget is tiny, so this exercises the machinery; it does not calibrate the glacier.
# Needs an executable built with -DUSE_MPI=ON. No mizuRoute topology is used.
#
# Usage:  ./test_calibration_gulkana.sh [population] [generations] [n_ranks]
# ---------------------------------------------------------------------------------------
set -euo pipefail

TEST_DIR="$(cd "$(dirname "$0")" && pwd)"
SUMMA_ROOT="$(cd "${TEST_DIR}/../../.." && pwd)"
DATA="${TEST_DIR}/gulkana"
WORK="${TEST_DIR}/gulkana_run"

POPULATION=${1:-8}
GENERATIONS=${2:-4}
N_RANKS=${3:-5}
N_SAMPLES=$((POPULATION * GENERATIONS))

SUMMA_EXE=""
for exe in summa_sundials_mizuroute_opt.exe summa_sundials_opt.exe summa_mizuroute_opt.exe summa_opt.exe; do
  if [ -x "${SUMMA_ROOT}/bin/${exe}" ]; then SUMMA_EXE="${SUMMA_ROOT}/bin/${exe}"; break; fi
done
if [ -z "${SUMMA_EXE}" ]; then
  echo "ERROR: no calibration executable found in ${SUMMA_ROOT}/bin"
  echo "       build one with -DUSE_MPI=ON"
  exit 1
fi

echo "======================================================================"
echo "SUMMA glacier calibration test (Gulkana, discharge + mass balance)"
echo "======================================================================"
echo "  executable:  ${SUMMA_EXE}"
echo "  work dir:    ${WORK}"
echo "  budget:      ${N_SAMPLES} trials (population ${POPULATION} x ${GENERATIONS} generations)"
echo "  ranks:       ${N_RANKS}"
echo

rm -rf "${WORK}"
mkdir -p "${WORK}/output" "${WORK}/state"
cp "${DATA}/summa_inputs/coldState.nc" "${WORK}/state/"
cat > "${WORK}/config.toml" <<EOF
# generated by test_calibration_gulkana.sh

[simulation]

case_name = "gulkana"

# one spinup year (2008) precedes the simulation, which the calibration then scores
start_time = "2009-01-01 00:00"
end_time   = "2012-12-31 23:00"
time_zone  = "utcTime"

use_mizuroute    = false
write_timeseries = false

work_path = "${WORK}/output"


[summa_files]

settings_path = "${DATA}/summa_inputs/"
forcing_path  = "${DATA}/forcing/"
state_path    = "${WORK}/state/"
output_path   = "${WORK}/output/"

init_condition = "coldState.nc"
attributes     = "attributes.nc"
forcing_list   = "forcingFileList.txt"

decisions        = "modelDecisions.txt"
output_control   = "outputControl.txt"
trial_params     = "trialParams.nc"
local_parameters = "localParamInfo.txt"
basin_parameters = "basinParamInfo.txt"

vegetation_table = "TBL_VEGPARM.TBL"
soil_table       = "TBL_SOILPARM.TBL"
general_table    = "TBL_GENPARM.TBL"
noahmp_table     = "TBL_MPTABLE.TBL"


[calibration]

algorithm = "nsga2"

start_date = "2009-01-01"
end_date   = "2012-12-31"

n_samples = ${N_SAMPLES}

param_list = [
    "frozenPrecipMultip",
    "tempCritRain",
    "albedoMax",
    "glacStor_kIce"
]

write_aligned = false


[calibration.nsga2]

population_size = ${POPULATION}


# discharge below the glacier: the GRU's routed runoff times its area
[[calibration.target]]

name      = "discharge"
variable  = "streamflow"
gru       = 1
obs_path  = "${DATA}/observations/"
obs_file  = "USGS_15478040_daily_flow.nc"
vname_obs = "q_obs"
metric    = "kge"


# winter and summer balances between the simulation's own extremes
[[calibration.target]]

name       = "mass_balance"
variable   = "basin__GlacierMassChange"
gru        = 1
obs_path   = "${DATA}/observations/"
obs_file   = "gulkana_mass_balance_seasonal.nc"
vname_obs  = "mb_obs"
accumulate = true
balance    = "seasonal"
metric     = "rmse"


# or basin storage against GRACE, in place of the mass balance
# [[calibration.target]]
#
# name           = "grace_tws"
# variable       = "basin__StorageChange"
# gru            = 1
# obs_path       = "${DATA}/observations/"
# obs_file       = "gulkana_grace_tws.nc"
# vname_obs      = "tws_obs"
# accumulate     = true
# baseline_start = "2009-01-01"
# baseline_end   = "2012-12-31"
# metric         = "rmse"
EOF

echo "Running nsga2..."
set +e
mpirun -np "${N_RANKS}" "${SUMMA_EXE}" -c "${WORK}/config.toml" > "${WORK}/run.log" 2>&1
status=$?
set -e
if [ ${status} -ne 0 ]; then
  echo "FAIL: calibration exited ${status}"
  echo "--- last 25 lines of ${WORK}/run.log ---"
  tail -25 "${WORK}/run.log"
  exit 1
fi
grep -E "^NSGA-II generation" "${WORK}/run.log" | sed 's/^/  /' || true
echo

echo "Checking the NSGA-II front..."
python3 - "${WORK}" "${POPULATION}" "${GENERATIONS}" <<'PYEOF'
import os, sys
import numpy as np
import netCDF4 as nc

work, pop, ngen = sys.argv[1], int(sys.argv[2]), int(sys.argv[3])

d = nc.Dataset(os.path.join(work, "output", "gulkana_calibration.nc"))
sense = [s.strip() for s in d["objective"].sense.split(",")]
obj = np.ma.filled(d["objective"][:].astype(float), np.nan).T   # (target, sample)
failed = np.asarray(d["trial_failed"][:]) == 1

def nondominated(f):
    n = f.shape[1]
    keep = np.ones(n, bool)
    for i in range(n):
        for j in range(n):
            if np.all(f[:, j] <= f[:, i]) and np.any(f[:, j] < f[:, i]):
                keep[i] = False
                break
    return keep

fail = False
def check(ok, what):
    global fail
    print(f"  {'ok  ' if ok else 'FAIL'} {what}")
    fail |= not ok

check(d.algorithm == "nsga2", "trials file records algorithm nsga2")
check(obj.shape == (2, pop * ngen), f"objective is 2 targets x {pop * ngen} trials")
check(sense == ["maximize", "minimize"], "discharge KGE is maximized, mass-balance RMSE minimized")
check(bool(np.all(np.isfinite(obj[:, ~failed]))), "every objective of a trial that ran is finite")
check(bool(np.all(np.abs(obj[:, ~failed]) < 1e5)), "every objective of a trial that ran is plausible")

# smaller is better on every row; a failed trial is the worst on every target
f = np.array([-o if s == "maximize" else o for o, s in zip(obj, sense)])
f[:, failed] = np.inf
front = np.asarray(d["pareto_front"][:]) == 1
check(bool(np.array_equal(front, nondominated(f))), "pareto_front flags exactly the non-dominated trials")

population = np.asarray(d["population"][:]) - 1
rank = np.asarray(d["population_rank"][:])
check(population.shape == (ngen, pop), f"population is {ngen} generations x {pop} members")
check(bool(np.all(front[population[-1][rank[-1] == 1]])), "the final population's first front is non-dominated overall")

nf = int(front.sum())
check(nf >= 1, f"the front holds {nf} trial(s)")

print()
print(f"  NSGA-II front ({nf} trials):")
for i in np.where(front)[0][np.argsort(-obj[0, front])]:
    print(f"    sample {i + 1:3d}: KGE {obj[0, i]:7.4f}   mass balance RMSE {obj[1, i]:7.1f} mm")
print(f"  failed trials (saved in output/failed_trials): {int(failed.sum())}")

sys.exit(1 if fail else 0)
PYEOF

echo
echo "PASS"
