#!/bin/bash
# ---------------------------------------------------------------------------------------
# Coupled SUMMA / MODFLOW 6 / mizuRoute calibration on Sagehen Creek, scoring discharge and
# stream temperature at USGS 10343500.
#
# The domain is the 9 D8 subcatchments of ex-gwf-sagehen, each with a stream HRU for its reach,
# built by utils/test/test_mflow/tools/build_sagehen9_calibration.py from the bundled basin-mean
# forcing (Oct 2016 - Sep 2018) in sagehen/forcing. NSGA-II scores water year 2018 after a
# water-year-2017 spin-up: discharge KGE and T_reach RMSE (degC) at reach 9, the outlet.
#
#   lumped  one land HRU per GRU (18 HRUs), mapped onto its GRU's cells; the default
#   grid    one land HRU per MODFLOW cell (3396 HRUs), hours per trial
#
# Needs bin/summa_modflow6_opt_sundials_mizuroute.exe, built with
# -DUSE_MPI=ON -DUSE_MIZUROUTE=ON -DUSE_MODFLOW6=ON, and a python3 with netCDF4 and pyproj.
#
# Usage:  ./test_calibration_sagehen.sh [lumped|grid] [population] [generations] [n_ranks]
# ---------------------------------------------------------------------------------------
set -euo pipefail

TEST_DIR="$(cd "$(dirname "$0")" && pwd)"
SUMMA_ROOT="$(cd "${TEST_DIR}/../../.." && pwd)"
DATA="${TEST_DIR}/sagehen"

LAYOUT=${1:-lumped}
POPULATION=${2:-6}
GENERATIONS=${3:-3}
N_RANKS=${4:-7}
N_SAMPLES=$((POPULATION * GENERATIONS))
WORK="${TEST_DIR}/sagehen_${LAYOUT}_run"
PYTHON=${PYTHON:-python3}

SUMMA_EXE="${SUMMA_ROOT}/bin/summa_modflow6_opt_sundials_mizuroute.exe"
if [ ! -x "${SUMMA_EXE}" ]; then
  echo "ERROR: ${SUMMA_EXE} not found"
  echo "       build it with -DUSE_MPI=ON -DUSE_MIZUROUTE=ON -DUSE_MODFLOW6=ON"
  exit 1
fi

echo "======================================================================"
echo "SUMMA coupled calibration test (Sagehen, discharge + stream temperature)"
echo "======================================================================"
echo "  executable:  ${SUMMA_EXE}"
echo "  layout:      ${LAYOUT}"
echo "  work dir:    ${WORK}"
echo "  budget:      ${N_SAMPLES} trials (population ${POPULATION} x ${GENERATIONS} generations)"
echo "  ranks:       ${N_RANKS}"
echo

rm -rf "${WORK}"
mkdir -p "${WORK}/output" "${WORK}/state"
echo "Building the ${LAYOUT} domain..."
"${PYTHON}" "${SUMMA_ROOT}/utils/test/test_mflow/tools/build_sagehen9_calibration.py" \
            "${LAYOUT}" "${DATA}/forcing" "${WORK}/domain" 2>&1 | grep -v -i deprecat
cp "${WORK}/domain/settings/SUMMA/coldState.nc" "${WORK}/state/"
echo

cat > "${WORK}/config.toml" <<EOF
# generated by test_calibration_sagehen.sh

[simulation]

case_name = "sagehen"

# one spinup year (water year 2017) precedes the simulation, which the calibration then scores
start_time = "2017-10-01 01:00"
end_time   = "2018-09-30 23:00"
time_zone  = "utcTime"

use_mizuroute    = true
use_modflow      = true
write_timeseries = false

work_path = "${WORK}/output"


[summa_files]

settings_path = "${WORK}/domain/settings/SUMMA/"
forcing_path  = "${WORK}/domain/forcing/"
state_path    = "${WORK}/state/"
output_path   = "${WORK}/output/"

init_condition = "coldState.nc"
attributes     = "attributes.nc"
forcing_list   = "forcingFileList.txt"

decisions        = "modelDecisions.txt"
output_control   = "outputControl.txt"
trial_params     = "trialParams.nc"
local_parameters = "localParamInfo.txt"
basin_parameters = "basinParamInfo.txt"

vegetation_table = "TBL_VEGPARM.TBL"
soil_table       = "TBL_SOILPARM.TBL"
general_table    = "TBL_GENPARM.TBL"
noahmp_table     = "TBL_MPTABLE.TBL"


[modflow]

config_file = "${WORK}/domain/summa_modflow6.config"
run_dir     = "${WORK}/domain/mf6"


[mizuRoute]

namelist_path = "${SUMMA_ROOT}/utils/test/test_mflow/domain_sagehen9/settings/mizuroute/"
namelist_file = "mizuroute.param"

methods = "3"
dt      = 3600

write_qbasin = false
write_Qreach = false


[hydrofabric]

hfabric_path = "${WORK}/domain/"
hfabric_file = "topology.nc"

dname_seg = "seg"
dname_hru = "hru"

varname_HRUid     = "hruId"
varname_segId     = "segId"
varname_hruSegId  = "hruToSegId"
varname_downSegId = "downSegId"

varname_area   = "area"
varname_slope  = "slope"
varname_length = "length"


[calibration]

algorithm = "nsga2"

start_date = "2017-10-01"
end_date   = "2018-09-30"

n_samples = ${N_SAMPLES}

param_list = [
    "frozenPrecipMultip",
    "tempCritRain",
    "k_macropore",
    "routingGammaScale"
]

write_aligned = false


[calibration.parameter_transformations]

k_macropore       = "log"
routingGammaScale = "log"


[calibration.nsga2]

population_size = ${POPULATION}


# discharge at the gauge, the outlet of reach 9
[[calibration.target]]

name      = "discharge"
variable  = "streamflow"
reach     = 9
obs_path  = "${DATA}/observations/"
obs_file  = "USGS_10343500_daily_flow.nc"
vname_obs = "q_obs"
metric    = "kge"


# water temperature leaving reach 9
[[calibration.target]]

name      = "stream_temperature"
variable  = "T_reach"
reach     = 9
obs_path  = "${DATA}/observations/"
obs_file  = "USGS_10343500_daily_temperature.nc"
vname_obs = "t_obs"
metric    = "rmse"
EOF

echo "Running nsga2..."
set +e
mpirun -np "${N_RANKS}" "${SUMMA_EXE}" -c "${WORK}/config.toml" > "${WORK}/run.log" 2>&1
status=$?
set -e
if [ ${status} -ne 0 ]; then
  echo "FAIL: calibration exited ${status}"
  echo "--- last 25 lines of ${WORK}/run.log ---"
  tail -25 "${WORK}/run.log"
  exit 1
fi
grep -E "^NSGA-II generation" "${WORK}/run.log" | sed 's/^/  /' || true
echo

echo "Checking the NSGA-II front..."
"${PYTHON}" - "${WORK}" "${POPULATION}" "${GENERATIONS}" <<'PYEOF'
import os, sys
import numpy as np
import netCDF4 as nc

work, pop, ngen = sys.argv[1], int(sys.argv[2]), int(sys.argv[3])

d = nc.Dataset(os.path.join(work, "output", "sagehen_calibration.nc"))
sense = [s.strip() for s in d["objective"].sense.split(",")]
obj = np.ma.filled(d["objective"][:].astype(float), np.nan).T   # (target, sample)
failed = np.asarray(d["trial_failed"][:]) == 1

fail = False
def check(ok, what):
    global fail
    print(f"  {'ok  ' if ok else 'FAIL'} {what}")
    fail |= not ok

check(obj.shape == (2, pop * ngen), f"objective is 2 targets x {pop * ngen} trials")
check(sense == ["maximize", "minimize"], "discharge KGE is maximized, temperature RMSE minimized")
check(not bool(failed.all()), f"{int((~failed).sum())} of {failed.size} trials ran")
ran = obj[:, ~failed]
check(bool(np.all(np.isfinite(ran))), "every objective of a trial that ran is finite")
# a daily stream temperature within a few degC of a mountain creek's, and the RMSE of a run that moves
check(bool(np.all((ran[1] > 0.0) & (ran[1] < 10.0))), "temperature RMSE is between 0 and 10 degC")
check(ran.shape[1] > 1 and bool(np.ptp(ran[1]) > 0.0), "temperature RMSE changes with the parameters")

front = np.asarray(d["pareto_front"][:]) == 1
print()
print(f"  NSGA-II front ({int(front.sum())} trials):")
for i in np.where(front)[0][np.argsort(-obj[0, front])]:
    print(f"    sample {i + 1:3d}: KGE {obj[0, i]:7.4f}   T_reach RMSE {obj[1, i]:6.3f} degC")
print(f"  failed trials (saved in output/failed_trials): {int(failed.sum())}")

sys.exit(1 if fail else 0)
PYEOF

echo
echo "PASS"
