#!/bin/bash
# ---------------------------------------------------------------------------------------
# Three-objective glacier calibration on the bundled Wolverine domain, routed by mizuRoute.
#
# NSGA-II on daily discharge (KGE) and water temperature (RMSE, degC) at USGS 15236900,
# the outlet of the one reach, and the glacier-wide seasonal mass balance (RMSE), 2017-2019
# after a 2016 spin-up, over eight parameters that move snow accumulation, melt and glacier
# runoff; and aquiferBaseflowRate and aquiferScaleFactor, on log scales, which set how much
# groundwater reaches the reach and how long the aquifer holds it. The groundwater leaves at the
# temperature of the bedrock base (deepTherml = bedrockLyrs), so no parameter sets its temperature.
# The script checks the front the way test_calibration_gulkana.sh does and prints it.
#
# The budget is tiny, so this exercises the machinery; it does not calibrate the glacier.
# Needs an executable built with -DUSE_MPI=ON -DUSE_MIZUROUTE=ON.
#
# Usage:  ./test_calibration_wolverine.sh [population] [generations] [n_ranks]
# ---------------------------------------------------------------------------------------
set -euo pipefail

TEST_DIR="$(cd "$(dirname "$0")" && pwd)"
SUMMA_ROOT="$(cd "${TEST_DIR}/../../.." && pwd)"
DATA="${TEST_DIR}/wolverine"
WORK="${TEST_DIR}/wolverine_run"

POPULATION=${1:-8}
GENERATIONS=${2:-4}
N_RANKS=${3:-5}
N_SAMPLES=$((POPULATION * GENERATIONS))

SUMMA_EXE=""
for exe in summa_sundials_mizuroute_opt.exe summa_mizuroute_opt.exe; do
  if [ -x "${SUMMA_ROOT}/bin/${exe}" ]; then SUMMA_EXE="${SUMMA_ROOT}/bin/${exe}"; break; fi
done
if [ -z "${SUMMA_EXE}" ]; then
  echo "ERROR: no calibration executable with mizuRoute found in ${SUMMA_ROOT}/bin"
  echo "       build one with -DUSE_MPI=ON -DUSE_MIZUROUTE=ON"
  exit 1
fi

echo "======================================================================"
echo "SUMMA glacier calibration test (Wolverine, discharge + temperature + mass balance)"
echo "======================================================================"
echo "  executable:  ${SUMMA_EXE}"
echo "  work dir:    ${WORK}"
echo "  budget:      ${N_SAMPLES} trials (population ${POPULATION} x ${GENERATIONS} generations)"
echo "  ranks:       ${N_RANKS}"
echo

rm -rf "${WORK}"
mkdir -p "${WORK}/output" "${WORK}/state"
cp "${DATA}/summa_inputs/coldState.nc" "${WORK}/state/"
cat > "${WORK}/config.toml" <<EOF
# generated by test_calibration_wolverine.sh

[simulation]

case_name = "wolverine"

# one spinup year (2016) precedes the simulation, which the calibration then scores
start_time = "2017-01-01 00:00"
end_time   = "2019-12-31 23:00"
time_zone  = "utcTime"

use_mizuroute    = true
write_timeseries = false

work_path = "${WORK}/output"


[summa_files]

settings_path = "${DATA}/summa_inputs/"
forcing_path  = "${DATA}/forcing/"
state_path    = "${WORK}/state/"
output_path   = "${WORK}/output/"

init_condition = "coldState.nc"
attributes     = "attributes.nc"
forcing_list   = "forcingFileList.txt"

decisions        = "modelDecisions.txt"
output_control   = "outputControl.txt"
trial_params     = "trialParams.nc"
local_parameters = "localParamInfo.txt"
basin_parameters = "basinParamInfo.txt"

vegetation_table = "TBL_VEGPARM.TBL"
soil_table       = "TBL_SOILPARM.TBL"
general_table    = "TBL_GENPARM.TBL"
noahmp_table     = "TBL_MPTABLE.TBL"


[mizuRoute]

namelist_path = "${DATA}/"
namelist_file = "mizuroute.param"

methods = "3"
dt      = 3600

write_qbasin = false
write_Qreach = false


[hydrofabric]

hfabric_path = "${DATA}/"
hfabric_file = "topology.nc"

dname_seg = "seg"
dname_hru = "hru"

varname_HRUid     = "hruId"
varname_segId     = "segId"
varname_hruSegId  = "hruToSegId"
varname_downSegId = "downSegId"

varname_area   = "area"
varname_slope  = "slope"
varname_length = "length"


[calibration]

algorithm = "nsga2"

start_date = "2017-01-01"
end_date   = "2019-12-31"

n_samples = ${N_SAMPLES}

param_list = [
    "frozenPrecipMultip",
    "tempCritRain",
    "albedoMax",
    "glacierWindFactor",
    "glacierTempReduction",
    "glacStor_kIce",
    "glacStor_kSnow",
    "glacStor_kFirn",
    "aquiferBaseflowRate",
    "aquiferScaleFactor"
]

write_aligned = false


[calibration.parameter_transformations]

aquiferBaseflowRate = "log"
aquiferScaleFactor  = "log"


[calibration.nsga2]

population_size = ${POPULATION}


# discharge at the gauge, the outlet of reach 1
[[calibration.target]]

name      = "discharge"
variable  = "streamflow"
reach     = 1
obs_path  = "${DATA}/observations/"
obs_file  = "USGS_15236900_daily_flow.nc"
vname_obs = "q_obs"
metric    = "kge"


# water temperature leaving reach 1
[[calibration.target]]

name      = "stream_temperature"
variable  = "T_reach"
reach     = 1
obs_path  = "${DATA}/observations/"
obs_file  = "USGS_15236900_daily_temperature.nc"
vname_obs = "t_obs"
metric    = "rmse"


# winter and summer balances between the simulation's own extremes
[[calibration.target]]

name       = "mass_balance"
variable   = "basin__GlacierMassChange"
gru        = 1
obs_path   = "${DATA}/observations/"
obs_file   = "wolverine_mass_balance_seasonal.nc"
vname_obs  = "mb_obs"
accumulate = true
balance    = "seasonal"
metric     = "rmse"
EOF

echo "Running nsga2..."
set +e
mpirun -np "${N_RANKS}" "${SUMMA_EXE}" -c "${WORK}/config.toml" > "${WORK}/run.log" 2>&1
status=$?
set -e
if [ ${status} -ne 0 ]; then
  echo "FAIL: calibration exited ${status}"
  echo "--- last 25 lines of ${WORK}/run.log ---"
  tail -25 "${WORK}/run.log"
  exit 1
fi
grep -E "^NSGA-II generation" "${WORK}/run.log" | sed 's/^/  /' || true
echo

echo "Checking the NSGA-II front..."
python3 - "${WORK}" "${POPULATION}" "${GENERATIONS}" <<'PYEOF'
import os, sys
import numpy as np
import netCDF4 as nc

work, pop, ngen = sys.argv[1], int(sys.argv[2]), int(sys.argv[3])

d = nc.Dataset(os.path.join(work, "output", "wolverine_calibration.nc"))
sense = [s.strip() for s in d["objective"].sense.split(",")]
obj = np.ma.filled(d["objective"][:].astype(float), np.nan).T   # (target, sample)
failed = np.asarray(d["trial_failed"][:]) == 1

def nondominated(f):
    n = f.shape[1]
    keep = np.ones(n, bool)
    for i in range(n):
        for j in range(n):
            if np.all(f[:, j] <= f[:, i]) and np.any(f[:, j] < f[:, i]):
                keep[i] = False
                break
    return keep

fail = False
def check(ok, what):
    global fail
    print(f"  {'ok  ' if ok else 'FAIL'} {what}")
    fail |= not ok

check(d.algorithm == "nsga2", "trials file records algorithm nsga2")
check(obj.shape == (3, pop * ngen), f"objective is 3 targets x {pop * ngen} trials")
check(sense == ["maximize", "minimize", "minimize"],
      "discharge KGE is maximized, temperature and mass-balance RMSE minimized")
check(not bool(failed.all()), f"{int((~failed).sum())} of {failed.size} trials ran")
ran = obj[:, ~failed]
check(bool(np.all(np.isfinite(ran))), "every objective of a trial that ran is finite")
# a glacier-fed creek runs at 0-3 degC, so a trial that ran misses it by a few degC at most
check(bool(np.all((ran[1] > 0.0) & (ran[1] < 10.0))), "temperature RMSE is between 0 and 10 degC")
check(bool(np.all(np.abs(ran[2]) < 1e5)), "every mass-balance RMSE is plausible")

# smaller is better on every row; a failed trial is the worst on every target
f = np.array([-o if s == "maximize" else o for o, s in zip(obj, sense)])
f[:, failed] = np.inf
front = np.asarray(d["pareto_front"][:]) == 1
check(bool(np.array_equal(front, nondominated(f))), "pareto_front flags exactly the non-dominated trials")

population = np.asarray(d["population"][:]) - 1
rank = np.asarray(d["population_rank"][:])
check(population.shape == (ngen, pop), f"population is {ngen} generations x {pop} members")
check(bool(np.all(front[population[-1][rank[-1] == 1]])), "the final population's first front is non-dominated overall")

nf = int(front.sum())
check(nf >= 1, f"the front holds {nf} trial(s)")

print()
print(f"  NSGA-II front ({nf} trials):")
for i in np.where(front)[0][np.argsort(-obj[0, front])]:
    print(f"    sample {i + 1:3d}: KGE {obj[0, i]:7.4f}   T_reach RMSE {obj[1, i]:6.3f} degC"
          f"   mass balance RMSE {obj[2, i]:7.1f} mm")
print(f"  failed trials (saved in output/failed_trials): {int(failed.sum())}")

sys.exit(1 if fail else 0)
PYEOF

echo
echo "PASS"
