#!/bin/bash
# ---------------------------------------------------------------------------------------
# Two-objective calibration test on the bundled Bow at Banff (CAN_05BB001) domain.
#
# The same domain and period as test_calibration_bow.sh, scored against two
# targets: daily discharge (KGE) and the GRACE storage anomaly (RMSE). The same sample
# budget is spent twice - by NSGA-II on the two objectives, and by DDS on their weighted
# sum - and the script checks the NSGA-II front, then compares what each search found.
#
# The budget is tiny, so this exercises the machinery; it does not settle which search is
# better. Needs an executable built with -DUSE_MPI=ON -DUSE_MIZUROUTE=ON.
#
# Usage:  ./test_calibration_bow_pareto.sh [population] [generations] [n_ranks]
# ---------------------------------------------------------------------------------------
set -euo pipefail

TEST_DIR="$(cd "$(dirname "$0")" && pwd)"
SUMMA_ROOT="$(cd "${TEST_DIR}/../../.." && pwd)"
DATA="${SUMMA_ROOT}/utils/test/test_mizuroute/bow_real_data"
WORK="${TEST_DIR}/bow_pareto"

POPULATION=${1:-8}
GENERATIONS=${2:-5}
N_RANKS=${3:-5}
N_SAMPLES=$((POPULATION * GENERATIONS))

# DDS weight on GRACE RMSE (mm) against discharge KGE: 100 mm counts as one unit of KGE
GRACE_WEIGHT=0.01

SUMMA_EXE="${SUMMA_ROOT}/bin/summa_sundials_mizuroute_opt.exe"
if [ ! -x "${SUMMA_EXE}" ]; then
  SUMMA_EXE="${SUMMA_ROOT}/bin/summa_mizuroute_opt.exe"
fi
if [ ! -x "${SUMMA_EXE}" ]; then
  echo "ERROR: no calibration executable found in ${SUMMA_ROOT}/bin"
  echo "       build one with -DUSE_MPI=ON -DUSE_MIZUROUTE=ON"
  exit 1
fi

echo "======================================================================"
echo "SUMMA two-objective calibration test (Bow at Banff, discharge + GRACE)"
echo "======================================================================"
echo "  executable:  ${SUMMA_EXE}"
echo "  work dir:    ${WORK}"
echo "  budget:      ${N_SAMPLES} trials (population ${POPULATION} x ${GENERATIONS} generations)"
echo "  ranks:       ${N_RANKS}"
echo

rm -rf "${WORK}"

# write_config <dir> <algorithm>
write_config() {
  local dir=$1 algorithm=$2
  mkdir -p "${dir}/output" "${dir}/state"
  cp "${DATA}/summa_inputs/coldState.nc" "${dir}/state/"
  cat > "${dir}/config.toml" <<EOF
# generated by test_calibration_bow_pareto.sh

[simulation]

case_name = "CAN_05BB001"

# one spinup year (2003) precedes the simulation, which the calibration then scores
start_time = "2004-01-01 00:00"
end_time   = "2004-12-31 23:00"
time_zone  = "utcTime"

use_mizuroute    = true
write_timeseries = false

work_path = "${dir}/output"


[summa_files]

settings_path = "${DATA}/summa_inputs/"
forcing_path  = "${DATA}/summa_inputs/"
state_path    = "${dir}/state/"
output_path   = "${dir}/output/"

init_condition = "coldState.nc"
attributes     = "attributes.nc"
forcing_list   = "forcingFileList_rdrs.txt"

decisions        = "modelDecisions.txt"
output_control   = "outputControl_short.txt"
trial_params     = "trialParams.nc"
local_parameters = "localParamInfo.txt"
basin_parameters = "basinParamInfo.txt"

vegetation_table = "TBL_VEGPARM.TBL"
soil_table       = "TBL_SOILPARM.TBL"
general_table    = "TBL_GENPARM.TBL"
noahmp_table     = "TBL_MPTABLE.TBL"


[mizuRoute]

namelist_path = "${DATA}/mizuroute_inputs/"
namelist_file = "mizuroute.param"

methods = "3"
dt      = 3600

write_qbasin = false
write_Qreach = false


[hydrofabric]

hfabric_path = "${DATA}/mizuroute_inputs/"
hfabric_file = "topology.nc"

dname_seg = "seg"
dname_hru = "hru"

varname_HRUid     = "hruId"
varname_segId     = "segId"
varname_hruSegId  = "hruToSegId"
varname_downSegId = "downSegId"

varname_area   = "area"
varname_slope  = "slope"
varname_length = "length"

seg_outlet = 710285850


[remapping]

remap_path = "${DATA}/mizuroute_inputs/"
remap_file = "lumped_to_hru.nc"

dname_hru  = "polyid"
dname_data = "data"

vname_hruid    = "polyid"
vname_num_qhru = "nOverlaps"
vname_weight   = "weight"
vname_qhruid   = "qhru_id"


[calibration]

algorithm = "${algorithm}"

start_date = "2004-01-01"
end_date   = "2004-12-31"

n_samples = ${N_SAMPLES}

param_list = [
    "k_soil",
    "aquiferScaleFactor",
    "routingGammaScale",
    "routingGammaShape"
]

write_aligned = false


[calibration.parameter_transformations]

k_soil = "log"


[calibration.nsga2]

population_size = ${POPULATION}



[[calibration.target]]

name      = "discharge"
variable  = "streamflow"
obs_path  = "${DATA}/observations/"
obs_file  = "CAN_05BB001_daily_flow_2002-2017.nc"
vname_obs = "q_obs"
metric    = "kge"
weight    = 1.0


[[calibration.target]]

name           = "grace_tws"
variable       = "basin__StorageChange"
obs_path       = "${DATA}/observations/"
obs_file       = "CAN_05BB001_grace_tws.nc"
vname_obs      = "tws_obs"
accumulate     = true
baseline_start = "2004-01-01"
baseline_end   = "2004-12-31"
metric         = "rmse"
weight         = ${GRACE_WEIGHT}
EOF
}

# run_search <algorithm>
run_search() {
  local algorithm=$1 dir="${WORK}/$1"
  write_config "${dir}" "${algorithm}"
  echo "Running ${algorithm}..."
  set +e
  mpirun -np "${N_RANKS}" "${SUMMA_EXE}" -c "${dir}/config.toml" > "${dir}/run.log" 2>&1
  local status=$?
  set -e
  if [ ${status} -ne 0 ]; then
    echo "FAIL: ${algorithm} calibration exited ${status}"
    echo "--- last 25 lines of ${dir}/run.log ---"
    tail -25 "${dir}/run.log"
    exit 1
  fi
  grep -E "^NSGA-II generation" "${dir}/run.log" | sed 's/^/  /' || true
}

run_search nsga2
run_search dds
echo

echo "Checking the NSGA-II front and comparing it with DDS..."
python3 - "${WORK}" "${POPULATION}" "${GENERATIONS}" "${GRACE_WEIGHT}" <<'PYEOF'
import os, sys
import numpy as np
import netCDF4 as nc

work, pop, ngen, grace_weight = sys.argv[1], int(sys.argv[2]), int(sys.argv[3]), float(sys.argv[4])

def load(algorithm):
    d = nc.Dataset(os.path.join(work, algorithm, "output", "CAN_05BB001_calibration.nc"))
    sense = [s.strip() for s in d["objective"].sense.split(",")]
    obj = np.ma.filled(d["objective"][:].astype(float), np.nan).T   # (target, sample)
    failed = np.asarray(d["trial_failed"][:]) == 1                  # the model refused or failed on these
    return d, obj, sense, failed

def oriented(obj, sense, failed):
    # smaller is better on every row; a failed trial is the worst on every target
    f = np.array([-o if s == "maximize" else o for o, s in zip(obj, sense)])
    f[:, failed] = np.inf
    return f

def nondominated(f):
    n = f.shape[1]
    keep = np.ones(n, bool)
    for i in range(n):
        for j in range(n):
            if np.all(f[:, j] <= f[:, i]) and np.any(f[:, j] < f[:, i]):
                keep[i] = False
                break
    return keep

def hypervolume(f, ref):
    # two objectives, smaller is better: area dominated by the points and bounded by ref
    pts = f[:, nondominated(f)].T
    pts = pts[np.argsort(pts[:, 0])]
    hv, prev = 0.0, ref[1]
    for x, y in pts:
        if x < ref[0] and y < prev:
            hv += (ref[0] - x) * (prev - y)
            prev = y
    return hv

fail = False
def check(ok, what):
    global fail
    print(f"  {'ok  ' if ok else 'FAIL'} {what}")
    fail |= not ok

d, obj, sense, failed = load("nsga2")
check(d.algorithm == "nsga2", "trials file records algorithm nsga2")
check(obj.shape == (2, pop * ngen), f"objective is 2 targets x {pop * ngen} trials")
check(sense == ["maximize", "minimize"], "discharge KGE is maximized, GRACE RMSE minimized")
check(bool(np.all(np.isfinite(obj[:, ~failed]))), "every objective of a trial that ran is finite")
check(bool(np.all(np.abs(obj[:, ~failed]) < 1e5)), "every objective of a trial that ran is plausible")

f = oriented(obj, sense, failed)
front = np.asarray(d["pareto_front"][:]) == 1
check(bool(np.array_equal(front, nondominated(f))), "pareto_front flags exactly the non-dominated trials")

born = np.asarray(d["birth_generation"][:])
check(bool(np.array_equal(born, np.repeat(np.arange(1, ngen + 1), pop))), "birth_generation numbers each generation")

population = np.asarray(d["population"][:]) - 1                 # (generation, member), 0-based samples
rank = np.asarray(d["population_rank"][:])
check(population.shape == (ngen, pop), f"population is {ngen} generations x {pop} members")
check(bool(np.all(front[population[-1][rank[-1] == 1]])), "the final population's first front is non-dominated overall")
check(all(set(population[g]) <= set(population[g - 1]) | set(range(g * pop, (g + 1) * pop))
          for g in range(1, ngen)), "each generation keeps only its parents and its own offspring")

nf = int(front.sum())
check(nf >= 1, f"the front holds {nf} trial(s)")

# compare with DDS on the weighted sum, same budget
dd, obj_dds, _, failed_dds = load("dds")
f_dds = oriented(obj_dds, sense, failed_dds)
ref = np.maximum(f[:, ~failed].max(axis=1), f_dds[:, ~failed_dds].max(axis=1))
hv_n, hv_d = hypervolume(f, ref), hypervolume(f_dds, ref)
front_dds = nondominated(f_dds)
beyond_dds = sum(not any(np.all(f_dds[:, j] <= f[:, i]) and np.any(f_dds[:, j] < f[:, i])
                         for j in range(f_dds.shape[1])) for i in np.where(front)[0])
scalar = obj_dds[0] - grace_weight * obj_dds[1]
best = int(np.nanargmax(scalar))

print()
print(f"  NSGA-II front ({nf} trials):")
for i in np.where(front)[0][np.argsort(-obj[0, front])]:
    print(f"    sample {i + 1:3d}: KGE {obj[0, i]:8.4f}   GRACE RMSE {obj[1, i]:8.2f} mm")
print(f"  DDS best weighted sum: sample {best + 1}: KGE {obj_dds[0, best]:8.4f}   GRACE RMSE {obj_dds[1, best]:8.2f} mm")
print(f"  DDS non-dominated trials: {int(front_dds.sum())}")
print(f"  NSGA-II front trials no DDS trial dominates: {beyond_dds} of {nf}")
print(f"  hypervolume (common reference): NSGA-II {hv_n:.4g}, DDS {hv_d:.4g}")
print(f"  failed trials (saved in output/failed_trials): NSGA-II {int(failed.sum())}, DDS {int(failed_dds.sum())}")

sys.exit(1 if fail else 0)
PYEOF

echo
echo "PASS"
