#!/bin/bash
# ---------------------------------------------------------------------------------------
# Twin experiment on Sagehen Creek: can discharge, stream temperature and heads recover known
# SUMMA and MODFLOW parameters?
#
# A reference trial of the calibration driver, with every searched parameter pinned to a known value
# away from its default (TRUTH below), writes the discharge and water temperature leaving reach 9 and
# the head at the OBS6 observation cells.  Those become the targets (make_sagehen_twin_targets.py).
# The same pinned trial, scored against them, must reproduce them.  Then NSGA-II searches the seven
# parameters from scratch against three objectives, discharge KGE, temperature RMSE and the head RMSE
# pooled over the cells, and the front member nearest the ideal point must recover every parameter
# within 10% of its searched range, on its search scale.
#
# The domain is test_calibration_sagehen.sh's lumped one (build_sagehen9_calibration.py), with GWE.
# Needs bin/summa_modflow6_opt_sundials_mizuroute.exe and a python3 with netCDF4 and pyproj.
#
# Usage:  ./test_calibration_sagehen_twin.sh [population] [generations] [n_ranks]
# ---------------------------------------------------------------------------------------
set -euo pipefail

TEST_DIR="$(cd "$(dirname "$0")" && pwd)"
SUMMA_ROOT="$(cd "${TEST_DIR}/../../.." && pwd)"
DATA="${TEST_DIR}/sagehen"
TOOLS="${SUMMA_ROOT}/utils/test/test_mflow/tools"

POPULATION=${1:-20}
GENERATIONS=${2:-10}
N_RANKS=${3:-10}
N_SAMPLES=$((POPULATION * GENERATIONS))
WORK="${TEST_DIR}/sagehen_twin_run"
PYTHON=${PYTHON:-python3}
SUMMA_EXE="${SUMMA_ROOT}/bin/summa_modflow6_opt_sundials_mizuroute.exe"

# name  truth  lower  upper  scale; the SUMMA parameters' bounds are their localParamInfo.txt bounds
PARAMS="K_mult        2.0     0.2   5.0   log
Sy_mult       0.7     0.5   1.5   linear
uzf_vks_mult  0.4     0.1   10.0  log
rhk_mult      3.0     0.1   10.0  log
KTS_mult      1.5     0.5   2.0   log
k_soil        3.0e-6  1e-7  1e-5  log
k_macropore   1.0e-2  1e-7  1e-1  log"
TOLERANCE=0.10
OBS_CELLS=$(cd "${TOOLS}" && "${PYTHON}" -c "from build_sagehen9_calibration import OBS_CELLS; print(' '.join(OBS_CELLS))")

if [ ! -x "${SUMMA_EXE}" ]; then
  echo "ERROR: ${SUMMA_EXE} not found"
  exit 1
fi

echo "======================================================================"
echo "SUMMA twin experiment (Sagehen, discharge + stream temperature + pooled heads)"
echo "======================================================================"
echo "  budget:      ${N_SAMPLES} trials (population ${POPULATION} x ${GENERATIONS} generations)"
echo "  ranks:       ${N_RANKS}"
echo "  heads at:    $(echo ${OBS_CELLS})"
echo

rm -rf "${WORK}"
mkdir -p "${WORK}"
echo "Building the lumped domain..."
"${PYTHON}" "${TOOLS}/build_sagehen9_calibration.py" lumped "${DATA}/forcing" "${WORK}/domain" 2>&1 | grep -v -i deprecat
cp "${DATA}/strt_spunup_lumped.txt" "${WORK}/domain/mf6/strt1.txt"

# the reference's settings: k_soil and k_macropore pinned to their true values, and an hourly output
# file, which mizuRoute's reach series join
cp -r "${WORK}/domain/settings/SUMMA" "${WORK}/domain/settings/SUMMA_ref"
"${PYTHON}" - "${WORK}/domain/settings/SUMMA_ref" "${PARAMS}" <<'PYEOF'
import os, sys
settings, params = sys.argv[1], [l.split() for l in sys.argv[2].splitlines()]
path = os.path.join(settings, "localParamInfo.txt")
truth = {p[0]: p[1] for p in params}
out = []
for line in open(path):
    key = line.split("|")[0].strip() if "|" in line else ""
    if key in truth:
        line = f"{key:<26}| {truth[key]:>12} | {truth[key]:>12} | {truth[key]:>12}\n"
    out.append(line)
open(path, "w").writelines(out)
with open(os.path.join(settings, "outputControl.txt"), "a") as f:
    f.write("scalarStreamTemp | 1\n")
PYEOF

# write_config <dir> <settings> <algorithm> <n_samples> <targets> <pinned>
write_config() {
  local dir=$1 settings=$2 algorithm=$3 samples=$4 targets=$5 pinned=$6
  mkdir -p "${dir}/output" "${dir}/state"
  cp "${WORK}/domain/settings/SUMMA/coldState.nc" "${dir}/state/"
  local write_ts=false
  [ "${pinned}" = "yes" ] && write_ts=true
  {
  cat <<EOF
# generated by test_calibration_sagehen_twin.sh

[simulation]

case_name = "sagehen"

# one spinup year (water year 2017) precedes the simulation, which the calibration then scores
start_time = "2017-10-01 01:00"
end_time   = "2018-09-30 23:00"
time_zone  = "utcTime"

use_mizuroute    = true
use_modflow      = true
write_timeseries = ${write_ts}

work_path = "${dir}/output"


[summa_files]

settings_path = "${WORK}/domain/settings/${settings}/"
forcing_path  = "${WORK}/domain/forcing/"
state_path    = "${dir}/state/"
output_path   = "${dir}/output/"

init_condition = "coldState.nc"
attributes     = "attributes.nc"
forcing_list   = "forcingFileList.txt"

decisions        = "modelDecisions.txt"
output_control   = "outputControl.txt"
trial_params     = "trialParams.nc"
local_parameters = "localParamInfo.txt"
basin_parameters = "basinParamInfo.txt"

vegetation_table = "TBL_VEGPARM.TBL"
soil_table       = "TBL_SOILPARM.TBL"
general_table    = "TBL_GENPARM.TBL"
noahmp_table     = "TBL_MPTABLE.TBL"


[modflow]

config_file = "${WORK}/domain/summa_modflow6.config"
run_dir     = "${WORK}/domain/mf6"


[mizuRoute]

namelist_path = "${SUMMA_ROOT}/utils/test/test_mflow/domain_sagehen9/settings/mizuroute/"
namelist_file = "mizuroute.param"

methods = "3"
dt      = 3600

write_qbasin = false
write_Qreach = ${write_ts}


[hydrofabric]

hfabric_path = "${WORK}/domain/"
hfabric_file = "topology.nc"

dname_seg = "seg"
dname_hru = "hru"

varname_HRUid     = "hruId"
varname_segId     = "segId"
varname_hruSegId  = "hruToSegId"
varname_downSegId = "downSegId"

varname_area   = "area"
varname_slope  = "slope"
varname_length = "length"


[calibration]

algorithm = "${algorithm}"

start_date = "2017-10-01"
end_date   = "2018-09-30"

n_samples = ${samples}

param_list = ["k_soil", "k_macropore"]

write_aligned = false


[calibration.parameter_transformations]

EOF
  echo "${PARAMS}" | awk '$5 == "log" {printf "%-13s = \"log\"\n", $1}'
  echo
  echo "${PARAMS}" | awk -v pinned="${pinned}" '
    $1 == "k_soil" || $1 == "k_macropore" {next}
    {
      lo = (pinned == "yes") ? $2 : $3; hi = (pinned == "yes") ? $2 : $4
      if ($1 == "K_mult")       files = "files = [\"kh1.txt\", \"kv1.txt\"]"
      if ($1 == "Sy_mult")      files = "files = \"sy1.txt\""
      if ($1 == "uzf_vks_mult") files = "files = \"sagehen.uzf\"\nblock = \"PACKAGEDATA\"\ncolumn = 8"
      if ($1 == "rhk_mult")     files = "files = \"sagehen.sfr\"\nblock = \"PACKAGEDATA\"\ncolumn = 10"
      if ($1 == "KTS_mult")     files = "files = \"kts1.txt\""
      printf "[[calibration.modflow_parameter]]\n\nname = \"%s\"\n%s\nlower = %s\nupper = %s\n\n", $1, files, lo, hi
    }'
  [ "${algorithm}" = "nsga2" ] && printf "[calibration.nsga2]\n\npopulation_size = %s\n\n" "${POPULATION}"
  cat "${targets}"
  } > "${dir}/config.toml"
}

# run <dir> <ranks>
run() {
  local dir=$1 ranks=$2 status
  set +e
  mpirun -np "${ranks}" "${SUMMA_EXE}" -c "${dir}/config.toml" > "${dir}/run.log" 2>&1
  status=$?
  set -e
  if [ ${status} -ne 0 ]; then
    echo "FAIL: ${dir} exited ${status}"
    tail -25 "${dir}/run.log"
    exit 1
  fi
}

# the twin's targets: discharge and temperature leaving reach 9, and the head at every OBS6 cell, pooled
TWIN_OBS="${WORK}/targets/SAGEHEN_TWIN_daily.nc"
names=$(for c in ${OBS_CELLS}; do printf '"%s", ' "$c"; done | sed 's/, $//')
vnames=$(for c in ${OBS_CELLS}; do printf '"h_%s", ' "$c"; done | sed 's/, $//')
cat > "${WORK}/twin_targets.toml" <<EOF
[[calibration.target]]

name      = "discharge"
variable  = "streamflow"
reach     = 9
obs_path  = "$(dirname "${TWIN_OBS}")/"
obs_file  = "$(basename "${TWIN_OBS}")"
vname_obs = "q_obs"
metric    = "kge"

[[calibration.target]]

name      = "stream_temperature"
variable  = "T_reach"
reach     = 9
obs_path  = "$(dirname "${TWIN_OBS}")/"
obs_file  = "$(basename "${TWIN_OBS}")"
vname_obs = "t_obs"
metric    = "rmse"

[[calibration.target]]

name      = "heads"
variable  = "modflow_obs"
obs_name  = [${names}]
obs_path  = "$(dirname "${TWIN_OBS}")/"
obs_file  = "$(basename "${TWIN_OBS}")"
vname_obs = [${vnames}]
metric    = "rmse"
EOF
# the reference trial is scored against the gauge, only so it runs as a calibration trial does
cat > "${WORK}/gauge_target.toml" <<EOF
[[calibration.target]]

name      = "discharge"
variable  = "streamflow"
reach     = 9
obs_path  = "${DATA}/observations/"
obs_file  = "USGS_10343500_daily_flow.nc"
vname_obs = "q_obs"
metric    = "kge"
EOF

echo "Running the reference trial at the true parameters..."
write_config "${WORK}/reference" SUMMA_ref dds 1 "${WORK}/gauge_target.toml" yes
run "${WORK}/reference" 2
mkdir -p "${WORK}/targets"
"${PYTHON}" "${TOOLS}/make_sagehen_twin_targets.py" \
  "$(ls "${WORK}"/reference/output/*_sample000001_timestep.nc)" \
  "${WORK}/reference/output/modflow_rank0001/sagehen.obs.csv" 9 "${TWIN_OBS}"
echo

echo "Scoring the true parameters against the targets..."
write_config "${WORK}/truth" SUMMA_ref dds 1 "${WORK}/twin_targets.toml" yes
run "${WORK}/truth" 2
echo

echo "Running nsga2..."
write_config "${WORK}/search" SUMMA nsga2 "${N_SAMPLES}" "${WORK}/twin_targets.toml" no
run "${WORK}/search" "${N_RANKS}"
grep -E "^NSGA-II generation" "${WORK}/search/run.log" | sed 's/^/  /' || true
echo

echo "Checking the recovery..."
"${PYTHON}" - "${WORK}" "${PARAMS}" "${TOLERANCE}" <<'PYEOF'
import os, sys
import numpy as np
import netCDF4 as nc

work, params, tol = sys.argv[1], [l.split() for l in sys.argv[2].splitlines()], float(sys.argv[3])

fail = False
def check(ok, what):
    global fail
    print(f"  {'ok  ' if ok else 'FAIL'} {what}")
    fail |= not ok

# the true parameters reproduce their own targets
t = nc.Dataset(os.path.join(work, "truth", "output", "sagehen_calibration.nc"))
f0 = np.asarray(t["objective"][:], float).ravel()
check(f0[0] > 0.9999 and f0[1] < 0.01 and f0[2] < 0.001,
      f"the true parameters reproduce the targets: KGE {f0[0]:.6f}, T RMSE {f0[1]:.2e} degC, head RMSE {f0[2]:.2e} m")

d = nc.Dataset(os.path.join(work, "search", "output", "sagehen_calibration.nc"))
obj = np.ma.filled(d["objective"][:].astype(float), np.nan).T   # (target, sample)
failed = np.asarray(d["trial_failed"][:]) == 1
front = (np.asarray(d["pareto_front"][:]) == 1) & ~failed
check(front.any(), f"{int(front.sum())} trials on the front, {int(failed.sum())} of {failed.size} failed")

# the front member nearest the ideal point, each objective scaled over the front and oriented to minimise
f = np.vstack([1.0 - obj[0], obj[1], obj[2]])[:, front]
span = np.where(np.ptp(f, axis=1) > 0, np.ptp(f, axis=1), 1.0)
best = np.where(front)[0][np.argmin(np.linalg.norm((f - f.min(axis=1)[:, None]) / span[:, None], axis=0))]
print(f"  front member nearest the ideal point: sample {best + 1}, KGE {obj[0, best]:.4f}, "
      f"T RMSE {obj[1, best]:.3f} degC, head RMSE {obj[2, best]:.3f} m")

print(f"  {'parameter':<14}{'truth':>10}{'found':>11}{'error':>9}   front range")
for name, truth, lo, hi, scale in params:
    truth, lo, hi = float(truth), float(lo), float(hi)
    s = np.log if scale == "log" else (lambda x: x)
    v = np.asarray(d[name][:], float)
    err = abs(s(v[best]) - s(truth)) / (s(hi) - s(lo))
    print(f"  {name:<14}{truth:>10.3g}{v[best]:>11.3g}{err:>8.1%}   {v[front].min():.3g} - {v[front].max():.3g}")
    check(err <= tol, f"{name} within {tol:.0%} of its range")

sys.exit(1 if fail else 0)
PYEOF

echo
echo "PASS"
